### ISSUE TITLE
base64 encoded images for normal captcha not working

### ISSUE THREAD

**Issue by guzman12345** [2captcha/2captcha-go#6]
base64 encoded image is not working, I keep getting a error stating no image was sent to the API. I made sure to leave the Image parameter blank and only leave the base64 parameter but I still get this error.

**Comment by 2captcha** [comment]
Could you please provide your code that doesn't work as expected?

**Comment by ArtemKremlyov** [comment]
Hi, also faced the same problem, here is a sample code:

`client := api2captcha.NewClient(os.Getenv("RUCAPTCHA_KEY"))
	client.DefaultTimeout = 300
	client.PollingInterval = 15
	client.RecaptchaTimeout = 300

	img := api2captcha.Normal{Base64: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCABkAK8DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKp6jczW0Mf2cIZZJVjXzM45Pt7VcrP1Lm50xP711k/hG5/pQBNp1095YRzyIqu2chTkcEjj8qZbanDc309oiSB4c5ZgNrYODjmuftNT1HT9Kt5fIzZsqeW0kIyQ2NuSshOTkfw0aNqdpHqV1NdXEcRZMksGVQTLJkZYDpgCgDraKjguIbmPzIJo5U6bo2DD8xUlABRRRQAUUUjMqKWYgKBkk9qAI7i4htIGmuJUiiXlnc4ArLbxNZAb1hvJIv+esdszLj14HT3rGRrjXb+GVQpmlXz4jKu5LOAnCMF7yP1Gegz6YNifTk+1vb29/ei/UDy7h52IaTBbayjgrgc5HcY5oA6S1u4L23We3lWSNujA1xmqX19Lc3X/E2u4gJp1hhi2KoWJQeoXcTnPerOlypLqNuRH5UWoI/mwg48q5iPzAY9Ru/7596xbznxLpu4/uRfXolHqrvFGP1kH5UAdrdao0Giw3SbDNKgKhhkZIycgelYuvaxcrp1tYmTF3c7fOaHKEBjgKOcgn9ACaZbOP+EesLq8YmK1iKShRklkYhgB3JZVAHuawLk3U+t/aXwbi3R5AAcqbp9saL7qpkCj3RqAN6yNzBZywWd5PvvbgQW7u+/Yij5pBn8f0q7batfwzywRS2+rrCxWRYmEc649jw36fjVRm+xNP9kwWs0TTbLPeZ8Fm+gyuf91q2v+Eb002VvbvCS8CgJOjFJAe53DnmgCzp+rWupBlhZllT78UilXX6g1V1xmLW8YlljTbLI3lSMhO1OOQQepFYlrvTWbXbM8zx6lJapM/LSQiAuwJHXDjb+FaOuanpwnktpZJElWB4muApMUBkAA3kdCcfh3xkUAbVjv8A7PtvMYs/lLuZjkk4HJqxWXc6vHp37uS2m8pCEEu6NVY4zgbnBP5dqW31y2n2kpLGjHaHbaVJ9MqSKANOsrWFnD2ssNvJMIzISI8ZBKFRwSPWtWigCpaWyrpVtbTRqyrCisjjI4A7Vw1mkU0s0djGFd2Ch4HKMG3MSBjHqOa63Wbp1lhso5Fj86N3YlwpYLtG1SehO7r7GqNjPFpEJudRsriB2wpcIHRBnAVdhJx79TQBbSG40iwijhdHurm4UO8oLDJHPcE8L61oabcveafDcSKqu4yQvTr2qhLqFtqL6ZLbS74/tZydpGMQu3Q/h+dWtDBGg6eT1NujH6lQaAL9Zuqao1m0dtbRrNeSglEZsKqjqzHsBWlXGzr9u1mWKUnbc3/2Z/8ArlHHu2fiefzoAVtTL5kl8RXq4PMlrYf6KD7uUbI/4GKm/ta4vtI1W0do53ghJF1b/wCrcEfocdRXUrGiRiNUUIBgKBwB6VBItnY2Dq6wwWqqdwACqAaAMfw8yDUL1RgFooGT/c2cflTIpks/Ek73B2qzPgnoMhcfotZNjM8FxbtZOJpoYyYATj7Zak5G0n+Jc9P8RWlealpl+ySCG+N2vytbpaszN/st8u0D3JGPWgCrb4/4SWNY+g1CSVR7GHB/n+tZcsRnutSZfvQxTSKfQ+ahz/45+lbfh+1kn1iW6k2nyd5YqcqJXOSgPfaoUZ9c1HpWl3Q1PVze2zwW8yvBE7sp8zdLIcqAScbSvUCgDKhvpJrueyhXIhuTLAh6NLJgpn2GWb64p1sIrfUZpFO+GyG/J/5aFMhT9TI7NWlpGiajaTXmoXFqv2uKAJbxLIGEjhMbs8YzgDnGOay10/UrPS4EFlK9xPP86oVk8sqNsYfaTwWO49cYoAvWlvd3tj5H9m2l5BDIWbfKUlMpyXZD9SQOn1p6x3iAwQR+IYgeDAjQlT/wN+QPpitbRY4ob028L7kgtUQkHOW8xwx+uVNXdX1RdNt12qJLmUlYYs43HGSSeygck9h+FAHOOsunSRj9zBcpEwijDbktIz96Rz3Y/rVzSNJF4sU06OtjG/mRRSfenfr5snqc8gdvyqLRtMbU3+2XTGS2Z/M3MMG5fsxHZB/CPxrrOAPQCgDndspvDcLbSXEcd9KWVNuR+7CD7xFVtTZbiYR29rLbSyqUdWAG/PA4BPTrms7UtaXz2tdGSO6uhLLMLtx+7hDHkjPBA6bjxxxk8Vu6FqNheCRj5ZvIgnnTeXsVy3Rlz2JBoA36KKKAGSwxTrtliSRfR1BFZd54esJ7dlt7eO2lyGVogUwwOQTtxWvRQBytroN7FJ5SjyotxYMZd+0ldpK9yccc9PeuniiWCFIkGERQqj2HFPooAK5bVrOO31KXz5Ggtb2RJYrpettdKNoP0ZQB6cEH71dTTJoYriF4Zo1kjcYZGGQR7igDN0zVJJJn0/UAkWoRDJC8LMvZ0z29R2P4E53iO4mudF1mBooxHGvlQHJLPNhWTjGPvEflRfeGJBGq2UomhjO5La4dgYz/ANM5R8yfqO3FU49M1K4uIkl+0RMrYSS8uEl2HHVFTqcd2oAv6NptpqHh8QXMIeOK7uBCwJDIBM4UqRyMDjilv9GjtNOubiW91C4jhiZxC10yBsDOCVwcVt2VpFYWcVrCD5cYwM9T6k+5PNSvGksbRyIrowwysMgj3FAHPjUP7MkmtrZtNEAceQn2nDBdo4CBSSd249e9T6dY3dxfjUb4KrfwJ36EDjsAC3HJ+Y/StJ3s9Oi3N5NunQYAXNNg1SyuZfKinBkPRWBUn6A9aAItRYreaZgkD7QxPviGSk0CFIdA08Iirm3jLbRjJ2jJNT3lhDfCMTGQeWxZTHIUOSCOoIPQmnsYdPseBshgjwB6KBwKAMXw8yvqWpEMCQSDg9D585/kRWTqltcXGpXUV3j7ZJKGtUc4iuYF58jPYnqR3wOoBFdDpOqR3rlRaC23qZF5B34ODnHfNXb6wttRtzBcxh0yCOcFSOhB6g+9AFe31myfSvtzv5ES/K6yDBRhwVI9e2K5DXNdudVkNogaG3Y7fIAJd89A4HJJ7Rj6sQOKreILzUINUNvcQ+VKzn7PKf8AVomPvD1c+vX0q7p+j3kNhLLBp4kR4yskk8hjmkU9RHj/AFfrzye/rQBz9xa3dwq2ls6wI7/O5w4yv3mY9HKgdvkU4VRnkRiSGa3n0ZHl3i2a9lZmO7exWOFSfVVYMf8AarT1KWDT9CgaO4e5e9UQwq8YjaOBDymBxkkYJHXism6tjodtb3twc3d7EZpWPUgzxED8hnHvQB0cfjG8W41mQzB4mvBaWERQYj2jDtwMtng4PcgDrT38V3U7W1m1zJETI8ckkNvmWQ9UAU8KTtkB904rG8K2JfxHpdtIMtDG91LnuSSAfxMaGtPxZoF1YXlz4gtZBiGaGeKID+LcN5P4D/x40Adf4flvpNMA1CKVJUdkVpcBpEH3WIHQ46+4Nalc8/iuLyop47C7NqzKHuJE8tEyffk49hXQ0AFFFFABRRRQAVzcqTLeTFUvI5UunkR47ferAoF6nj1rpKKAMSzfU31CEub02/zeb58cSL04xt+bOa2XYIjOeigk06mTIZIJEHVlI/SgDn7G3OsXUlzOx2Drt4JzyFB7ADBOOpNGsabFZxRy25ZEL7Su4kAnoR6HNN0q8/s23kWVG2HgMBkK6jaQ3pnANUb3Vbm9tbcX3k24Z87EJLAf3iPT+fpQB1tpKZ7KCVurxqx/EZrH8T3iw2kduWVfNbLFjgYHr9TgVtW7RtbRNCcxFAUP+zjisBnXU9aeNZTt3bGEchVgi9eQcgFiB+FAFS1ZLQ5ti8sVowkEuxgGVuHGSOfWutUhlDA5BGQaxb/R7aCFbi1tczRtk7QWd16EZPJ4q5ozTf2cqTRSRmMlF8wYJUdDj6UAXXjjkxvRWwcjcM4NZniO6ez0O4eINvYCMMqltueNxx2FatZ2p3VxA9vHbtEplLbmljLgBVLcAEenrQB59Z2kfiPxVGITu063UW8HoYkxvb8That/EG3afxDpiiMmGK2eSTA4AV1NbliDYQtfWGjSRy3ADyPsUIwPPCiQlc5z0NN1K0vdbvbO5t4omgkg8q4xKMxgyK3TvwpoAoeFbbyPF9wX++lmLYE/7Gwn9WNbXifVLaOM6RLDO73cRCyIFKoSQBuyc8kjoDVTVbZ9O1eS8DSQo7CWK4WMuqPjDK4HO1hjn2qpAx1nWoJPPiupjKjyG3VvLhjQ5wSR1JxxQBZ8MWltq0D3Woh7q8jcf65ywUEAjC9B3HTtXX1wUVvqthezw2MV6hDNG7JbgrIu7chDMR0DEdKv2WlawdTtbt0mjMb5ke6vPMZkPUbVG0fhQB11FFFABRRRQAUUUUAVNTujZ6fLMv38bUHqx4H61i6DfTFoWnuJZUnLRkynO1x8y/QFf6U/xM7TBLWNgNi+Y3BOSx2KOATk5Yjjqoqm4u3ldpLd7ZZgixFYsKsq8oSS2e2OnpQB0U2lWVxKZZIfnPVlYqT9cEZpRpdisJiFpFsPJBXOfxqSyulvLOK4UY3rkqeqnuPwNT0ANRFjjWNFCooACjoBTY7eGEsYoY4yxySqgZqSigAooooAKzNUAN5p4PQySD/yE9adZ2qJN5ljNDbyT+TOWdIyobaY3X+IgdWHegDBTVdVtNJtisDGAxokTm2GWBAC9JjyeO1a3h628u1a4LKTMAMKc4xnr75JzVizsS/h61srtCri2SNwDyrBQOCO4NVLA3trqhhltpCkoPmSqo2Fx0cem4dR6igDcooooAKKKKACiiigAooooAKKKKAOeX99roL85uW/8cTA/ma1dVjWTS7kN/ChcEdivIP5gUUUAUvDZZ7CSV3LGSQuRxgE9cVs0UUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAH//2Q=="}
	code, err := client.Solve(img.ToRequest())`

**Comment by kratzky** [comment]
should be fixed in #3
